# Generated by Django 4.0.4 on 2023-01-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Base', '0002_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('restaurant_groups', models.ManyToManyField(related_name='restaurant_groups', to='auth.group')),
            ],
        ),
    ]
