# Generated by Django 4.0.4 on 2023-01-06 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='name',
            new_name='username',
        ),
    ]
