# Generated by Django 4.1.7 on 2023-03-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_remove_restaurant_username_restaurant_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
